name: Build for Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK and Configure Linker
      run: |
        sdkmanager --install "ndk;25.2.9519653"
        echo '' >> .cargo/config.toml
        echo 'linker = "/usr/lib/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang"' >> .cargo/config.toml

    - name: Build the project
      run: cargo build --release --target aarch64-linux-android

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cosmic-term-android
        path: target/aarch64-linux-android/release/cosmic-term
