name: Build for aarch64-musl

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain and musl target
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-unknown-linux-musl

    - name: Install musl-tools for cross-compilation
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Build the project
      run: |
        export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc
        cargo build --release --target aarch64-unknown-linux-musl

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cosmic-term-musl
        path: target/aarch64-unknown-linux-musl/release/cosmic-term
